---
# Install MapR Core components for all machines

# Redhat / CentOS
- name: Install mapr-core (Redhat / CentOS)
  yum: name={{ item }} state=present
  with_items:
  - mapr-core
  - mapr-core-internal
  - mapr-kafka
  when: ansible_os_family == 'RedHat'
# Debian / Ubuntu
- name: Install mapr-core (Debian / Ubuntu)
  apt: name={{ item }} state=present allow_unauthenticated=yes
  with_items:
  - mapr-core
  - mapr-core-internal
  - mapr-kafka
  when: ansible_os_family == 'Debian'

# Suse
- name: Install mapr-core (Suse)
  zypper: name={{ item }} state=present
  with_items:
  - mapr-compat-suse
  - mapr-core
  - mapr-core-internal
  - mapr-kafka
  when: ansible_os_family == 'Suse'
