---
# Debian / Ubuntu
- name: Install pre-required packages for R
  apt: name={{ item }} state=present update_cache=yes
  with_items:
  - unixodbc
  - unixodbc-dev
  when: ansible_os_family == 'Debian'
- name: Install R Lang
  apt: name={{ item }} state=present update_cache=yes
  with_items:
  - r-base
  - r-base-core
  when: ansible_os_family == 'Debian'

- name: Create lib folder in MapR-FS
  file: path="/mapr/{{ cluster_name }}/R-Shared/shared-libs" state=directory mode=0777
- name: Find Spark Path
  find: paths="/opt/mapr/spark" patterns="spark*" file_type=directory
  register: spark_path_result
  failed_when: spark_path_result.matched != 1
- name: Find Hadoop Streaming Jar Path
  find: paths="/opt/mapr/hadoop/hadoop-{{ hadoop_version }}/share/hadoop/tools/lib/" patterns="hadoop-streaming-*" file_type=file
  register: streaming_jar_path_result
  failed_when: streaming_jar_path_result.matched != 1
- debug: msg="Streaming JAR Path {{ streaming_jar_path_result.files[0].path }}"
# copy Renviron
- name: Copy Renviron file
  template: src=Renviron.ubuntu dest=/usr/lib/R/etc/Renviron
  when: ansible_os_family == 'Debian'
