---
# Install Hive CLI
# Redhat / CentOS
- name: Install mapr-hive (Redhat / CentOS)
  yum: name=mapr-hive state=present
  when: ansible_os_family == 'RedHat'
# Debian / Ubuntu
- name: Install mapr-hive (Debian / Ubuntu)
  apt: name=mapr-hive state=present allow_unauthenticated=yes
  when: ansible_os_family == 'Debian'
# Suse
- name: Install mapr-hive (Suse)
  zypper: name=mapr-hive state=present
  when: ansible_os_family == 'Suse'

# Other actions
- name: Create hive mysql db
  mysql_db: name={{ hive_db_schema }} state=present login_host={{ hive_db_host }} login_user={{ mapr_mysql_user }} login_password={{ mapr_mysql_password }}
  when: hive_db_host is defined
#- name: Downloading MySQL Driver
#  unarchive: src={{ mysql_jdbc_url }} dest=/tmp copy=no
#- name: Copy mysql driver
#  copy: remote_src=True src=/tmp/mysql-connector-java-{{ mysql_jdbc_version }}/mysql-connector-java-{{ mysql_jdbc_version }}-bin.jar dest=/opt/mapr/hive/hive-{{ hive_version }}/lib/
- name: Copy mysql driver
  copy: src=mysql-connector-java-5.1.40-bin.jar dest=/opt/mapr/hive/hive-{{ hive_version }}/lib/
  when: hive_db_host is defined
- name: Configure hive-site.xml
  template: src=hive-site.unsecure.xml dest=/opt/mapr/hive/hive-{{ hive_version }}/conf/hive-site.xml
  when: hive_server_security == 'none'
- name: Configure hive-site.xml - unsecure
  template: src=hive-site.unsecure.xml dest=/opt/mapr/hive/hive-{{ hive_version }}/conf/hive-site.xml
  when: hive_server_security == 'none'
- name: Configure hive-site.xml - maprsasl
  template: src=hive-site.maprsasl.xml dest=/opt/mapr/hive/hive-{{ hive_version }}/conf/hive-site.xml
  when: hive_server_security == 'maprsasl'
- name: Configure hive-site.xml - pam
  template: src=hive-site.pam.xml dest=/opt/mapr/hive/hive-{{ hive_version }}/conf/hive-site.xml
  when: hive_server_security == 'pam'
- name: Configure hive-env.sh
  template: src=hive-env.sh dest=/opt/mapr/hive/hive-{{ hive_version }}/conf/hive-env.sh
- name: Add HIVE_HOME to /etc/profile
  lineinfile: dest=/etc/profile state=present line="export HIVE_HOME=/opt/mapr/hive/hive-{{ hive_version }}/"
- name: Set owner mapr-system user
  file: path=/opt/mapr/hive owner={{ mapr_user }} group={{ mapr_group }} state=directory recurse=yes