Vagrant.configure("2") do |config|
  config.vm.box = "devproof/mapr-6.0.1-centos"
#  config.vm.network :private_network, ip: "192.168.56.15"
  config.vm.network "forwarded_port", guest: 8443, host: 8443
  config.vm.network "forwarded_port", guest: 7222, host: 7222
  config.vm.network "forwarded_port", guest: 7221, host: 7221
  config.vm.network "forwarded_port", guest: 5660, host: 5660
  config.vm.network "forwarded_port", guest: 5692, host: 5692
  config.vm.network "forwarded_port", guest: 5724, host: 5724
  config.vm.network "forwarded_port", guest: 5756, host: 5756
  config.vm.network "forwarded_port", guest: 1111, host: 1111
  config.vm.network "forwarded_port", guest: 2049, host: 2049
  config.vm.network "forwarded_port", guest: 8099, host: 8099
  config.vm.network "forwarded_port", guest: 8042, host: 8042
  config.vm.network "forwarded_port", guest: 8044, host: 8044
  config.vm.network "forwarded_port", guest: 8033, host: 8033
  config.vm.network "forwarded_port", guest: 8090, host: 8090
end