Vagrant.configure("2") do |config|
  config.vm.box = "devproof/mapr-6.0.1-centos"
#  config.vm.network :private_network, ip: "192.168.56.15"
  config.vm.network "forwarded_port", guest: 8443, host: 8443
end